version: '3.8'
services:
  backend:
    build:
      context: .
    volumes:
      - ./:/app           # mount source for live edit
      - /app/node_modules # avoid overwriting node_modules from container
    command: npm run dev  # run nodemon in dev
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://mongo:27017/ecommerce
    ports:
      - "5000:5000"
